hello_world::algorithms::controller::pid::PidList
typedef PidNode* hello_world::algorithms::controller::pid::PidList::iterator
定义迭代器类型
typedef const PidNode* hello_world::algorithms::controller::pid::PidList::const_iterator
定义常量迭代器类型
size_t hello_world::algorithms::controller::pid::PidList::size_
链表的大小
Referenced by push, removeTail, size.
PidNode* hello_world::algorithms::controller::pid::PidList::head_ptr_
链表的头指针
Referenced by begin, begin, empty, push, removeTail.
PidNode* hello_world::algorithms::controller::pid::PidList::tail_ptr_
链表的尾指针
Referenced by empty, push, removeTail.
hello_world::algorithms::controller::pid::PidList::PidList()
默认构造函数，初始化 PidList
hello_world::algorithms::controller::pid::PidList::~PidList()
析构函数，清空链表
References clear.
hello_world::algorithms::controller::pid::PidList::PidList(const PidList &)=delete
禁止复制构造
PidList & hello_world::algorithms::controller::pid::PidList::operator=(const PidList &)=delete
禁止赋值操作
void hello_world::algorithms::controller::pid::PidList::push(const BasicPid &obj)
向链表尾部添加一个新的 PidNode
obj 要添加的 BasicPid 对象
References hello_world::algorithms::controller::pid::BasicPid::params, push.
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid, hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid, push.
void hello_world::algorithms::controller::pid::PidList::push(const BasicPidParams &params)
向链表尾部添加一个新的 PidNode
params 要添加的 BasicPidParams 对象
References empty, head_ptr_, hello_world::algorithms::controller::pid::PidNode::next_ptr_, size_, tail_ptr_.
void hello_world::algorithms::controller::pid::PidList::removeTail()
移除链表尾部的 PidNode
References empty, head_ptr_, hello_world::algorithms::controller::pid::PidNode::next_ptr_, size_, tail_ptr_.
Referenced by clear.
void hello_world::algorithms::controller::pid::PidList::clear()
清空链表
References empty, removeTail.
Referenced by ~PidList.
bool hello_world::algorithms::controller::pid::PidList::empty() const
检查链表是否为空
如果链表为空则返回 true，否则返回 false
References head_ptr_, tail_ptr_.
Referenced by clear, push, removeTail.
size_t hello_world::algorithms::controller::pid::PidList::size() const
获取链表的大小
链表的大小
References size_.
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc, hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid, hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid, hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc, hello_world::algorithms::controller::pid::MultiNodesPid::reset, hello_world::algorithms::controller::pid::MultiNodesPid::size.
iterator hello_world::algorithms::controller::pid::PidList::begin()
获取链表的开始迭代器
链表的开始迭代器 当链表为空时，返回nullptr
References head_ptr_.
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc, hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc, hello_world::algorithms::controller::pid::MultiNodesPid::paramsAt, hello_world::algorithms::controller::pid::MultiNodesPid::reset.
iterator hello_world::algorithms::controller::pid::PidList::end()
获取链表的结束迭代器
链表的结束迭代器 实际是nulllptr，仅供判断迭代结束使用
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc, hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc, hello_world::algorithms::controller::pid::MultiNodesPid::paramsAt, hello_world::algorithms::controller::pid::MultiNodesPid::reset.
const_iterator hello_world::algorithms::controller::pid::PidList::begin() const
获取链表的开始常量迭代器
链表的开始常量迭代器 当链表为空时，返回nullptr
References head_ptr_.
const_iterator hello_world::algorithms::controller::pid::PidList::end() const
获取链表的结束常量迭代器
链表的结束常量迭代器 实际是nulllptr，仅供判断迭代结束使用