hello_world::devices::referee::Referee
RxStatus
RxPackage<CompetitionStatus> hello_world::devices::referee::Referee::competition_status_
RxPackage<CompetitionResult> hello_world::devices::referee::Referee::competition_result_
RxPackage<CompetitionRobotsHp> hello_world::devices::referee::Referee::competition_robots_hp_
RxPackage<TeamEvent> hello_world::devices::referee::Referee::team_event_
RxPackage<TeamSupplierAction> hello_world::devices::referee::Referee::team_supplier_action_
RxPackage<TeamRefereeWarning> hello_world::devices::referee::Referee::team_referee_warning_
RxPackage<RobotDartStatus> hello_world::devices::referee::Referee::robot_dart_status_
RxPackage<RobotPerformance> hello_world::devices::referee::Referee::robot_performance_
Referenced by encodeFrame.
RxPackage<RobotPowerHeat> hello_world::devices::referee::Referee::robot_power_heat_
RxPackage<RobotPosition> hello_world::devices::referee::Referee::robot_position_
RxPackage<RobotBuff> hello_world::devices::referee::Referee::robot_buff_
RxPackage<RobotAerialStatus> hello_world::devices::referee::Referee::robot_aerial_status_
RxPackage<RobotDamage> hello_world::devices::referee::Referee::robot_damage_
RxPackage<RobotShootData> hello_world::devices::referee::Referee::robot_shoot_data_
RxPackage<RobotProjectileAllowance> hello_world::devices::referee::Referee::robot_projectile_allowance_
RxPackage<RobotRfid> hello_world::devices::referee::Referee::robot_rfid_
RxPackage<RobotDartClientCommand> hello_world::devices::referee::Referee::robot_dart_client_command_
RxPackage<RobotsGroundPosition> hello_world::devices::referee::Referee::robots_ground_position_
RxPackage<RobotRadarMarkProgress> hello_world::devices::referee::Referee::robot_radar_mark_progress_
RxPackage<InterCustomCtrllerToRobot> hello_world::devices::referee::Referee::inter_custom_controller_to_robot_
RxPackage<InterClientMapToRobots> hello_world::devices::referee::Referee::inter_client_map_to_robots_
RxPackage<InterCtrllerToRobot> hello_world::devices::referee::Referee::inter_controller_to_robot_
RxPackageInterRadarWarning hello_world::devices::referee::Referee::inter_radar_warning_
FrameHeader hello_world::devices::referee::Referee::frame_header
FrameCmdId hello_world::devices::referee::Referee::frame_cmd_id
Referenced by encodeFrame.
struct hello_world::devices::referee::Referee::__REFEREE_PACKED hello_world::devices::referee::Referee::header
uint8_t hello_world::devices::referee::Referee::frame_raw[kRefereeMaxBuffer][kRefereeMaxBuffer]
RxStatus hello_world::devices::referee::Referee::rx_status
size_t hello_world::devices::referee::Referee::frame_data_index
size_t hello_world::devices::referee::Referee::frame_expect_length
InterFrameHeader hello_world::devices::referee::Referee::inter_frame_header
struct hello_world::devices::referee::Referee::__REFEREE_PACKED hello_world::devices::referee::Referee::header
const size_t hello_world::devices::referee::Referee::kRefereeRxPackageNumber
Referenced by decodeRxPackage.
RxPackageInfo* const hello_world::devices::referee::Referee::kRefereeRxPackagePtrs[kRefereeRxPackageNumber][kRefereeRxPackageNumber]
Referenced by decodeRxPackage.
size_t hello_world::devices::referee::Referee::last_updated_frame_index_
Referenced by decodeRxPackage.
struct hello_world::devices::referee::Referee hello_world::devices::referee::Referee::rx_info_
Referenced by processByte, restartDecodeFrame.
union hello_world::devices::referee::Referee hello_world::devices::referee::Referee::tx_info_
Referenced by encodeFrame.
bool hello_world::devices::referee::Referee::decodeFrame(const uint8_t *p_frame, const size_t _frame_length)
References processByte.
bool hello_world::devices::referee::Referee::processByte(const uint8_t byte)
References decodeRxPackage, hello_world::devices::referee::kFramePartIndexCmdId, hello_world::devices::referee::kFramePartLengthExceptData, hello_world::devices::referee::kFramePartLengthHeader, hello_world::devices::referee::kRefereeFrameHeaderSof, hello_world::devices::referee::kRefereeMaxBuffer, kRxStatusCmdDataTail, kRxStatusHeader, kRxStatusWaitingHeaderSof, restartDecodeFrame, rx_info_, hello_world::devices::referee::VerifyCrc16CheckSum, hello_world::devices::referee::VerifyCrc8CheckSum.
Referenced by decodeFrame.
void hello_world::devices::referee::Referee::restartDecodeFrame(size_t frame_length=kRefereeMaxBuffer)
References kRxStatusWaitingHeaderSof, rx_info_.
Referenced by processByte.
bool hello_world::devices::referee::Referee::encodeFrame(const T &data, const FrameCmdId frame_cmd_id, const uint16_t sub_content_id, const uint16_t receiver_id, uint8_t *p_frame, size_t &frame_length)
References encodeSetCrc, frame_cmd_id, hello_world::devices::referee::kFrameCmdIdInterAmongRobots, hello_world::devices::referee::kFramePartIndexData, hello_world::devices::referee::kFramePartLengthExceptData, hello_world::devices::referee::kRefereeFrameHeaderSof, hello_world::devices::referee::kRefereeMaxBuffer, hello_world::devices::referee::kUiSubCmdIdDeleteLayer, hello_world::devices::referee::kUiSubCmdIdDrawCharacter, hello_world::devices::referee::kUiSubCmdIdDrawGraphic1, hello_world::devices::referee::kUiSubCmdIdDrawGraphic2, hello_world::devices::referee::kUiSubCmdIdDrawGraphic5, hello_world::devices::referee::kUiSubCmdIdDrawGraphic7, robot_performance_, tx_info_.
bool hello_world::devices::referee::Referee::decodeRxPackage(const uint8_t *p_frame_cmd_data)
References hello_world::devices::referee::RxPackageInfo::decode, kRefereeRxPackageNumber, kRefereeRxPackagePtrs, last_updated_frame_index_.
Referenced by processByte.
bool hello_world::devices::referee::Referee::encodeSetCrc(uint8_t *p_frame, size_t frame_length)
References hello_world::devices::referee::kFramePartLengthHeader, hello_world::devices::referee::SetEndCrc16CheckSum, hello_world::devices::referee::SetEndCrc8CheckSum.
Referenced by encodeFrame.