hello_world::algorithms::controller::pid::OutLimit
float hello_world::algorithms::controller::pid::OutLimit::lower_
输出下限
float hello_world::algorithms::controller::pid::OutLimit::upper_
输出上限
hello_world::algorithms::controller::pid::OutLimit::OutLimit(float lower=-0.1f, float upper=0.1f)
State hello_world::algorithms::controller::pid::OutLimit::setLower(float lower)
References hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk.
State hello_world::algorithms::controller::pid::OutLimit::setUpper(float upper)
References hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk.
State hello_world::algorithms::controller::pid::OutLimit::setParams(float lower, float upper)
References hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk.
bool hello_world::algorithms::controller::pid::OutLimit::isLegal()
float hello_world::algorithms::controller::pid::OutLimit::calc(float out)
Referenced by hello_world::algorithms::controller::pid::BasicPid::calc, hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc, hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc.
bool hello_world::algorithms::controller::pid::OutLimit::handleIllegalParams()
处理非法参数
如果存在非法参数返回true，否则返回false