hello_world::devices::imu::BMI088
SPI_HandleTypeDef* const hello_world::devices::imu::BMI088::kHspi_
Referenced by accMultiRead, accRead, accWrite, BMI088, gyroMultiRead, gyroRead, gyroWrite.
GPIO_TypeDef* const hello_world::devices::imu::BMI088::kAccCsPort_
IMU 对应的 SPI 句柄的指针
Referenced by accCsH, accCsL, BMI088.
const uint32_t hello_world::devices::imu::BMI088::kAccCsPin_
加速度计片选端口
Referenced by accCsH, accCsL, BMI088.
GPIO_TypeDef* const hello_world::devices::imu::BMI088::kGyroCsPort_
加速度计片选引脚
Referenced by BMI088, gyroCsH, gyroCsL.
const uint32_t hello_world::devices::imu::BMI088::kGyroCsPin_
陀螺仪片选端口
Referenced by BMI088, gyroCsH, gyroCsL.
BMI088Config hello_world::devices::imu::BMI088::config_
Referenced by accInit, BMI088, getAccData, getGyroData, gyroInit.
float hello_world::devices::imu::BMI088::rot_mat_flatten_[9][9]
Referenced by BMI088.
arm_matrix_instance_f32 hello_world::devices::imu::BMI088::rot_mat_
Referenced by BMI088, getData.
hello_world::devices::imu::BMI088::BMI088(const BMI088HWConfig &hw_config, const float rot_mat_flatten[9], const BMI088Config &config=BMI088Config())
BMI088 初始化
hw_config 硬件配置 rot_mat_flatten 旋转矩阵（展平） [r00 r01 r02 r10 r11 r12 r20 r21 r22]，使用后可释放 config 设备配置 None None
References hello_world::devices::imu::BMI088Config::acc_odr, hello_world::devices::imu::BMI088Config::acc_osr, hello_world::devices::imu::BMI088Config::acc_range, accCsH, config_, hello_world::devices::imu::BMI088Config::gyro_odr_fbw, hello_world::devices::imu::BMI088Config::gyro_range, gyroCsH, HW_ASSERT, kAccCsPin_, kAccCsPort_, hello_world::devices::imu::kBMI088AccOdr12_5, hello_world::devices::imu::kBMI088AccOdr1600, hello_world::devices::imu::kBMI088AccOsr4, hello_world::devices::imu::kBMI088AccOsrNormal, hello_world::devices::imu::kBMI088AccRange24G, hello_world::devices::imu::kBMI088AccRange3G, hello_world::devices::imu::kBMI088GyroRange125Dps, hello_world::devices::imu::kBMI088GyroRange2000Dps, kGyroCsPin_, kGyroCsPort_, kHspi_, rot_mat_, rot_mat_flatten_.
virtual hello_world::devices::imu::BMI088::~BMI088()
BMI088ErrState hello_world::devices::imu::BMI088::init(bool self_test=false) const
进行 BMI088 芯片配置
self_test 是否开启传感器自检测 错误状态 该函数内部会阻塞运行，请不要在中断中调用
References accInit, gyroInit, hello_world::devices::imu::kBMI088ErrStateNoErr.
void hello_world::devices::imu::BMI088::getData(float acc_data[3], float gyro_data[3], float *temp) const
获取传感器数据
acc_data 加速度计三轴数据，[ax ay az]，单位：m/s^2 gyro_data 陀螺仪三轴数据，[wx wy wz]，单位：rad/s temp_ptr 温度数据指针，单位：℃ None 传入 null_ptr 则不获取对应数据
References hello_world::devices::imu::DelayUs, getAccData, getGyroData, getTemp, hello_world::devices::imu::kCommWaitTime, rot_mat_.
void hello_world::devices::imu::BMI088::accCsL(void) const
陀螺仪片选引脚
References kAccCsPin_, kAccCsPort_.
Referenced by accMultiRead, accRead, accWrite.
void hello_world::devices::imu::BMI088::accCsH(void) const
References kAccCsPin_, kAccCsPort_.
Referenced by accMultiRead, accRead, accWrite, BMI088.
void hello_world::devices::imu::BMI088::gyroCsL(void) const
References kGyroCsPin_, kGyroCsPort_.
Referenced by gyroMultiRead, gyroRead, gyroWrite.
void hello_world::devices::imu::BMI088::gyroCsH(void) const
References kGyroCsPin_, kGyroCsPort_.
Referenced by BMI088, gyroMultiRead, gyroRead, gyroWrite.
BMI088ErrState hello_world::devices::imu::BMI088::accInit(bool self_test) const
加速度计配置
self_test 是否进行自检测 None 错误状态
References _BMI088_ACC_ACC_CONF_ACC_ODR_SHFITS, _BMI088_ACC_ACC_CONF_ACC_OSR_SHFITS, hello_world::devices::imu::BMI088Config::acc_odr, hello_world::devices::imu::BMI088Config::acc_osr, hello_world::devices::imu::BMI088Config::acc_range, accRead, accSelfTest, accWrite, BMI088_ACC_ACC_CHIP_ID, BMI088_ACC_ACC_CHIP_ID_VALUE, BMI088_ACC_ACC_CONF, BMI088_ACC_ACC_PWR_CONF, BMI088_ACC_ACC_PWR_CONF_ACTIVE_MODE, BMI088_ACC_ACC_PWR_CTRL, BMI088_ACC_ACC_PWR_CTRL_ON, BMI088_ACC_ACC_RANGE, BMI088_ACC_ACC_SOFTRESET, BMI088_ACC_ACC_SOFTRESET_VALUE, config_, hello_world::devices::imu::DelayUs, hello_world::devices::imu::kAccResetTime, hello_world::devices::imu::kBMI088ErrStateAccConfigErr, hello_world::devices::imu::kBMI088ErrStateAccNotFound, hello_world::devices::imu::kBMI088ErrStateAccSelfTestFailed, hello_world::devices::imu::kBMI088ErrStateNoErr, hello_world::devices::imu::kCheckWaitTime, hello_world::devices::imu::kCommWaitTime.
Referenced by init.
BMI088ErrState hello_world::devices::imu::BMI088::gyroInit(bool self_test) const
陀螺仪配置
self_test 是否进行自检测 None 错误状态
References BMI088_GYRO_GYRO_BANDWIDTH, BMI088_GYRO_GYRO_BANDWIDTH_MUST_SET, BMI088_GYRO_GYRO_CHIP_ID, BMI088_GYRO_GYRO_CHIP_ID_VALUE, BMI088_GYRO_GYRO_LPM1, BMI088_GYRO_GYRO_LPM1_NORMAL, BMI088_GYRO_GYRO_RANGE, BMI088_GYRO_GYRO_SOFTRESET, BMI088_GYRO_GYRO_SOFTRESET_VALUE, config_, hello_world::devices::imu::DelayUs, hello_world::devices::imu::BMI088Config::gyro_odr_fbw, hello_world::devices::imu::BMI088Config::gyro_range, gyroRead, gyroSelfTest, gyroWrite, hello_world::devices::imu::kBMI088ErrStateGyroConfigErr, hello_world::devices::imu::kBMI088ErrStateGyroNotFound, hello_world::devices::imu::kBMI088ErrStateGyroSelfTestFailed, hello_world::devices::imu::kBMI088ErrStateNoErr, hello_world::devices::imu::kCheckWaitTime, hello_world::devices::imu::kCommWaitTime, hello_world::devices::imu::kGyroResetTime.
Referenced by init.
BMI088ErrState hello_world::devices::imu::BMI088::accSelfTest(void) const
加速度计自检测
错误状态 None
References accRead, accWrite, BMI088_ACC_ACC_CONF, BMI088_ACC_ACC_CONF_ACC_ODR_1600_HZ, BMI088_ACC_ACC_CONF_NORMAL, BMI088_ACC_ACC_PWR_CONF, BMI088_ACC_ACC_PWR_CONF_ACTIVE_MODE, BMI088_ACC_ACC_PWR_CTRL, BMI088_ACC_ACC_PWR_CTRL_ON, BMI088_ACC_ACC_RANGE, BMI088_ACC_ACC_RANGE_ACC_RANGE_24G, BMI088_ACC_ACC_SELF_TEST, BMI088_ACC_ACC_SELF_TEST_NEGATIVE_SIGNAL, BMI088_ACC_ACC_SELF_TEST_POSITIVE_SIGNAL, hello_world::devices::imu::DelayUs, getAccData, hello_world::devices::imu::kAccSelfTestLongDelay, hello_world::devices::imu::kAccSelfTestShortDelay, hello_world::devices::imu::kBMI088ErrStateAccSelfTestFailed, hello_world::devices::imu::kBMI088ErrStateNoErr, hello_world::devices::imu::kCheckWaitTime, hello_world::devices::imu::kCommWaitTime, hello_world::kGravAcc.
Referenced by accInit.
BMI088ErrState hello_world::devices::imu::BMI088::gyroSelfTest(void) const
陀螺仪自检测
错误状态 None
References BMI088_GYRO_GYRO_SELF_TEST, BMI088_GYRO_GYRO_SELF_TEST_BIST_FAIL, BMI088_GYRO_GYRO_SELF_TEST_BIST_RDY, BMI088_GYRO_GYRO_SELF_TEST_TRIG_BIST, hello_world::devices::imu::DelayUs, gyroRead, gyroWrite, hello_world::devices::imu::kBMI088ErrStateGyroSelfTestFailed, hello_world::devices::imu::kBMI088ErrStateNoErr, hello_world::devices::imu::kCommWaitTime.
Referenced by gyroInit.
void hello_world::devices::imu::BMI088::getGyroData(float gyro_data[3]) const
获取陀螺仪数据
gyro_data 陀螺仪三轴数据，[wx wy wz]，单位：rad/s None None
References BMI088_GYRO_RATE_X_LSB, config_, hello_world::devices::imu::BMI088Config::gyro_range, gyroMultiRead, hello_world::devices::imu::kGyroRawDataLen, hello_world::devices::imu::kGyroSens.
Referenced by getData.
void hello_world::devices::imu::BMI088::getAccData(float acc_data[3]) const
获取加速度计数据
acc_data 加速度计三轴数据，[ax ay az]，单位：m/s^2 None None
References hello_world::devices::imu::BMI088Config::acc_range, accMultiRead, BMI088_ACC_ACC_X_LSB, config_, hello_world::devices::imu::kAccRawDataLen, hello_world::devices::imu::kAccSens.
Referenced by accSelfTest, getData.
float hello_world::devices::imu::BMI088::getTemp(void) const
获取温度数据
温度，单位：℃ None
References _BMI088_ACC_TEMP_LSB_SHIFTS, _BMI088_ACC_TEMP_MSB_SHIFTS, accMultiRead, BMI088_ACC_TEMP_MSB, hello_world::devices::imu::kTempOffset, hello_world::devices::imu::kTempRawDataLen, hello_world::devices::imu::kTempSens.
Referenced by getData.
void hello_world::devices::imu::BMI088::gyroWrite(uint8_t mem_addr, uint8_t value) const
向陀螺仪寄存器写入数据
mem_addr 寄存器地址 value 待写入数据 None None
References gyroCsH, gyroCsL, kHspi_, hello_world::devices::imu::kSpiTimeout, hello_world::devices::imu::kWriteSign.
Referenced by gyroInit, gyroSelfTest.
uint8_t hello_world::devices::imu::BMI088::gyroRead(uint8_t mem_addr) const
读取陀螺仪寄存器数据
mem_addr 寄存器地址 读取数据 None
References gyroCsH, gyroCsL, kHspi_, hello_world::devices::imu::kPaddingValue, hello_world::devices::imu::kReadSign, hello_world::devices::imu::kSpiTimeout.
Referenced by gyroInit, gyroSelfTest.
void hello_world::devices::imu::BMI088::gyroMultiRead(uint8_t start_mem_addr, uint8_t len, uint8_t rx_data[]) const
陀螺仪多寄存器数据读取
start_mem_addr 寄存器起始地址 len 带读取数据长度 rx_data 读取得到的数据 None None
References gyroCsH, gyroCsL, kHspi_, hello_world::devices::imu::kPaddingData, hello_world::devices::imu::kReadSign, hello_world::devices::imu::kSpiTimeout.
Referenced by getGyroData.
void hello_world::devices::imu::BMI088::accWrite(uint8_t mem_addr, uint8_t value) const
向加速度计寄存器写入数据
mem_addr 寄存器地址 value 待写入数据 None None
References accCsH, accCsL, kHspi_, hello_world::devices::imu::kSpiTimeout, hello_world::devices::imu::kWriteSign.
Referenced by accInit, accSelfTest.
uint8_t hello_world::devices::imu::BMI088::accRead(uint8_t mem_addr) const
读取加速度计寄存器数据
mem_addr 寄存器地址 读取数据 None
References accCsH, accCsL, kHspi_, hello_world::devices::imu::kPaddingValue, hello_world::devices::imu::kReadSign, hello_world::devices::imu::kSpiTimeout.
Referenced by accInit, accSelfTest.
void hello_world::devices::imu::BMI088::accMultiRead(uint8_t start_mem_addr, uint8_t len, uint8_t rx_data[]) const
加速度计多寄存器数据读取
start_mem_addr 寄存器起始地址 len 带读取数据长度 rx_data 读取得到的数据 None None
References accCsH, accCsL, kHspi_, hello_world::devices::imu::kPaddingData, hello_world::devices::imu::kPaddingValue, hello_world::devices::imu::kReadSign, hello_world::devices::imu::kSpiTimeout.
Referenced by getAccData, getTemp.