hello_world::algorithms::controller::pid::MultiNodesPid
typedef BasicPidParams hello_world::algorithms::controller::pid::MultiNodesPid::Params
定义 Params 类型为 BasicPidParams
typedef MultiNodesPidType hello_world::algorithms::controller::pid::MultiNodesPid::Type
定义 Type 类型为 MultiNodesPidType
PidList hello_world::algorithms::controller::pid::MultiNodesPid::pid_list_
PID 控制器列表
Referenced by cascade_calc, MultiNodesPid, MultiNodesPid, parallel_calc, paramsAt, reset, size.
OutLimit hello_world::algorithms::controller::pid::MultiNodesPid::out_limit_
输出限制
Referenced by cascade_calc, parallel_calc.
Type hello_world::algorithms::controller::pid::MultiNodesPid::type_
PID 类型
Referenced by calc, MultiNodesPid, MultiNodesPid.
float hello_world::algorithms::controller::pid::MultiNodesPid::out_
PID 输出
Referenced by cascade_calc, out, parallel_calc, reset.
hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid(Type type, OutLimit out_limit, size_t count)
构造函数，初始化 MultiNodesPid 对象，至少会存在一个 PID 控制器节点，推荐和 paramsAt 函数一起使用
type PID 类型 out_limit 输出限制 count PID 数量 如果 count 为 0，则将其设置为 1。 然后，根据 count 的值创建相应数量的 PID 控制器，并将它们添加到 pid_list_ 中。 反馈值维数为 PID 控制器节点的数量。 如果 type 为 kParallel，则将参考值维数与反馈值维数相同。 前馈值维数和输出值维数始终为 1。 如果需要修改 PID 参数，推荐使用 paramsAt 函数 相较于初始化时确定参数更加安全、灵活，不必预先声明参数数组
References hello_world::algorithms::controller::Controller::fdb_dim_, pid_list_, hello_world::algorithms::controller::pid::PidList::push, hello_world::algorithms::controller::Controller::ref_dim_, hello_world::algorithms::controller::pid::PidList::size, type_.
hello_world::algorithms::controller::pid::MultiNodesPid::MultiNodesPid(Type type, OutLimit out_limit, size_t count, const Params *params_arr)
构造函数，初始化 MultiNodesPid 对象，至少会存在一个 PID 控制器节点
type PID 类型 out_limit 输出限制 count PID 数量 params_arr PID 参数数组 如果 count 为 0，则将其设置为 1。 如果 params_arr 为 nullptr，则使用默认参数创建 PID 控制器。 然后，根据 count 的值创建相应数量的 PID 控制器，并将它们添加到 pid_list_ 中。 反馈值维数为 PID 控制器节点的数量。 如果 type 为 kParallel，则将参考值维数与反馈值维数相同。 前馈值维数和输出值维数始终为 1。 如果需要修改 PID 参数，推荐使用 paramsAt 函数
References hello_world::algorithms::controller::Controller::fdb_dim_, pid_list_, hello_world::algorithms::controller::pid::PidList::push, hello_world::algorithms::controller::Controller::ref_dim_, hello_world::algorithms::controller::pid::PidList::size, type_.
State hello_world::algorithms::controller::pid::MultiNodesPid::reset() override
重置 PID 控制器
始终返回 kStateOk
References hello_world::algorithms::controller::pid::PidList::begin, hello_world::algorithms::controller::pid::PidList::end, hello_world::algorithms::controller::kStateOk, hello_world::algorithms::controller::pid::PidNode::next_ptr_, hello_world::algorithms::controller::pid::PidNode::obj_, out_, pid_list_, hello_world::algorithms::controller::pid::BasicPid::reset, hello_world::algorithms::controller::pid::PidList::size.
State hello_world::algorithms::controller::pid::MultiNodesPid::calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls) override
计算 PID 控制器的输出
ref_ls 参考值数组 fdb_ls 反馈值数组 ffd_ls 前馈值数组 out_ls 输出值数组 表示计算过程是否正常的状态值 - 如果类型是 kCascade，则调用 cascade_calc 函数计算输出； - 如果类型是 kParallel，则调用 parallel_calc 函数计算输出； - 否则，返回错误状态 kStateError MultiNodesPidType cascade_calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls) parallel_calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls)
References cascade_calc, hello_world::algorithms::controller::kStateError, parallel_calc, type_.
size_t hello_world::algorithms::controller::pid::MultiNodesPid::size() const
获取 PID 控制器的数量
PID 控制器的数量
References pid_list_, hello_world::algorithms::controller::pid::PidList::size.
float hello_world::algorithms::controller::pid::MultiNodesPid::out() const
获取 PID 控制器的输出
PID 控制器的输出
References out_.
Referenced by cascade_calc, parallel_calc.
MultiNodesPid::Params & hello_world::algorithms::controller::pid::MultiNodesPid::paramsAt(size_t idx)
获取指定索引处 PID 控制器的参数
idx PID 控制器的索引 指定索引处 PID 控制器的参数。如果索引超出 PID 控制器列表的范围，返回最后一个 PID 控制器的参数。
References hello_world::algorithms::controller::pid::PidList::begin, hello_world::algorithms::controller::pid::PidList::end, hello_world::algorithms::controller::pid::PidNode::next_ptr_, hello_world::algorithms::controller::pid::PidNode::obj_, hello_world::algorithms::controller::pid::BasicPid::params, pid_list_.
State hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls)
计算级联 PID 控制器的输出
ref_ls 参考值数组，只使用第一个值，如果为nullptr则使用 0 fdb_ls 反馈值数组，将使用等同于 size() 个数的值，如果为 nullptr 将不会进行计算，且会将输出置零 ffd_ls 前馈值数组，只使用第一个值，如果为 nullptr 则使用 0 out_ls 输出值数组，只使用第一个值，为 nullptr 时输出传递失败 表示计算过程是否正常的状态值 kStateOk 计算成功且所有参数均不为 nullptr kStateError 有参数为 nullptr，计算成功与否视参数而定 - 当 ref_ls 为 nullptr 时，使用 0 作为参考值 - 当 fdb_ls 为 nullptr 时，计算失败，并将输出置零 - 当 ffd_ls 为 nullptr 时，使用 0 作为前馈值 - 当 out_ls 为 nullptr 时，输出传递失败
References hello_world::algorithms::controller::pid::PidList::begin, hello_world::algorithms::controller::pid::BasicPid::calc, hello_world::algorithms::controller::pid::OutLimit::calc, hello_world::algorithms::controller::pid::PidList::end, hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk, hello_world::algorithms::controller::pid::PidNode::next_ptr_, hello_world::algorithms::controller::pid::PidNode::obj_, out, out_, out_limit_, pid_list_, hello_world::algorithms::controller::pid::PidList::size.
Referenced by calc.
State hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls)
计算并行 PID 控制器的输出
ref_ls 参考值数组，将使用等同于 size() 个数的值，如果为 nullptr 将不会进行计算，且会将输出置零 fdb_ls 反馈值数组，将使用等同于 size() 个数的值，如果为 nullptr 将不会进行计算，且会将输出置零 ffd_ls 前馈值数组，只使用第一个值，如果为 nullptr 则使用 0 out_ls 输出值数组，只使用第一个值，为 nullptr 时输出传递失败 表示计算过程是否正常的状态值 kStateOk 计算成功且所有参数均不为 nullptr kStateError 有参数为 nullptr，计算成功与否视参数而定 - 当 ref_ls 为 nullptr 时，计算失败，并将输出置零 - 当 fdb_ls 为 nullptr 时，计算失败，并将输出置零 - 当 ffd_ls 为 nullptr 时，使用 0 作为前馈值 - 当 out_ls 为 nullptr 时，输出传递失败
References hello_world::algorithms::controller::pid::PidList::begin, hello_world::algorithms::controller::pid::BasicPid::calc, hello_world::algorithms::controller::pid::OutLimit::calc, hello_world::algorithms::controller::pid::PidList::end, hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk, hello_world::algorithms::controller::pid::PidNode::next_ptr_, hello_world::algorithms::controller::pid::PidNode::obj_, out, out_, out_limit_, pid_list_, hello_world::algorithms::controller::pid::PidList::size.
Referenced by calc.