hello_world::devices::motor::DM_J4310
uint8_t hello_world::devices::motor::DM_J4310::temp_
Referenced by decode, temp.
bool hello_world::devices::motor::DM_J4310::is_start_
电机温度
Referenced by decode, DM_J4310, encode.
constexpr uint32_t hello_world::devices::motor::DM_J4310::kTx0_
电机使能
Referenced by DM_J4310.
constexpr uint32_t hello_world::devices::motor::DM_J4310::kRx0_
Referenced by DM_J4310.
hello_world::devices::motor::DM_J4310::DM_J4310(uint8_t id, const OptionalParams &optinal_params=OptionalParams())
DM_J4310 初始化
id 电机 ID，1到10 optinal_params 电机可选配置参数 None None
References hello_world::devices::motor::MotorInfo::angle_offset, hello_world::devices::motor::OptionalParams::angle_offset, hello_world::devices::motor::MotorInfo::angle_range, hello_world::devices::motor::OptionalParams::angle_range, hello_world::devices::motor::Motor::curr2torq, hello_world::devices::motor::MotorBaseInfo::curr_input_lim, hello_world::devices::motor::MotorInfo::dir, hello_world::devices::motor::OptionalParams::dir, hello_world::devices::motor::OptionalParams::ex_redu_rat, HW_ASSERT, hello_world::devices::motor::MotorInfo::id, hello_world::devices::motor::Motor::id, hello_world::devices::motor::MotorInfo::input_type, hello_world::devices::motor::OptionalParams::input_type, is_start_, hello_world::devices::motor::kAngleRange0To2Pi, hello_world::devices::motor::kAngleRangeNegInfToPosInf, hello_world::devices::motor::kAngleRangeNegPiToPosPi, hello_world::devices::motor::kDirFwd, hello_world::devices::motor::kDirRev, hello_world::devices::motor::kDM_J4310MotorBaseInfo, hello_world::devices::motor::kInputTypeCurr, hello_world::devices::motor::kInputTypeRaw, hello_world::devices::motor::kInputTypeTorq, hello_world::devices::motor::kInvalidValue, hello_world::devices::motor::kMaxTorq, kRx0_, kTx0_, hello_world::devices::motor::OptionalParams::max_curr_input_lim, hello_world::devices::motor::OptionalParams::max_torq_input_lim, hello_world::Min, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::MotorBaseInfo::raw_input_lim, hello_world::devices::motor::MotorBaseInfo::redu_rat, hello_world::devices::motor::OptionalParams::remove_build_in_reducer, hello_world::devices::motor::MotorInfo::rx_id, hello_world::devices::motor::Motor::torq2curr, hello_world::devices::motor::MotorBaseInfo::torq_input_lim, hello_world::devices::motor::MotorInfo::tx_id.
virtual hello_world::devices::motor::DM_J4310::~DM_J4310()
State hello_world::devices::motor::DM_J4310::setInput(float input)
设定发给电调的期望值
input 发给电调的期望值 运行状态 1. 期望值的物理意义与电机当前的输入类型有关，可使用 get_input_type 方法查看 设定的期望值会自动被限制到允许的范围内，当前实际的设定值可以通 过 getInput 方法查看
References hello_world::Bound, curr2raw, hello_world::devices::motor::Motor::curr2torq, hello_world::devices::motor::Motor::curr_input_, hello_world::devices::motor::MotorBaseInfo::curr_input_lim, hello_world::devices::motor::MotorInfo::input_type, hello_world::devices::motor::kInputTypeCurr, hello_world::devices::motor::kInputTypeRaw, hello_world::devices::motor::kInputTypeTorq, hello_world::devices::motor::kStateInputTypeError, hello_world::devices::motor::kStateInputValueOverflow, hello_world::devices::motor::kStateOk, hello_world::devices::motor::Motor::motor_info_, raw2torq, hello_world::devices::motor::Motor::raw_input_, hello_world::devices::motor::Motor::torq2curr, torq2raw, hello_world::devices::motor::Motor::torq_input_, hello_world::devices::motor::MotorBaseInfo::torq_input_lim.
State hello_world::devices::motor::DM_J4310::encode(uint8_t tx_data[8], uint32_t tx_msg_std_id) const override
将要发给电调的期望输值编码为对应的 CAN 报文
tx_data 将要发出的 CAN 报文 tx_msg_std_id 发给电调的报文的ID 当 ID 匹配时返回 kStateOk，否则返回 kStateIdDismatch 1. 只有当 tx_msg_std_id 与实际的发给电机报文的 ID 对应时才会生成 报文，该 ID 可以通过 tx_id 方法获取 只会在报文需要的位置上进行修改，区域位置的内容会保持不变
References hello_world::Bound, HW_ASSERT, is_start_, hello_world::devices::motor::kStateIdDismatch, hello_world::devices::motor::kStateOk, hello_world::devices::motor::kTorqBits, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::Motor::raw_input_, hello_world::devices::motor::MotorInfo::tx_id.
State hello_world::devices::motor::DM_J4310::decode(const uint8_t rx_data[8], uint32_t rx_msg_std_id) override
将电调发回的 CAN 报文进行解包
rx_data 电调发回的 CAN 报文 rx_msg_std_id 电调发回的报文的ID 当 ID 匹配时返回 kStateOk，否则返回 kStateIdDismatch 只有当 rx_msg_std_id 与实际的电机会发回报文的 ID 对应时才会对报文 进行解包，该 ID 可以通过 rx_id 方法获取
References hello_world::devices::motor::_Uint2Float, hello_world::devices::motor::Motor::actual_angle_, hello_world::devices::motor::Motor::angle, hello_world::devices::motor::Motor::angle_, hello_world::devices::motor::MotorInfo::angle_offset, hello_world::devices::motor::MotorInfo::angle_range, hello_world::devices::motor::Motor::curr_, hello_world::devices::motor::MotorInfo::dir, HW_ASSERT, is_start_, hello_world::devices::motor::kAngleBits, hello_world::devices::motor::kAngleRangeNegInfToPosInf, hello_world::devices::motor::Motor::kCross0ValueThres, hello_world::devices::motor::kMaxAngle, hello_world::devices::motor::kMaxVel, hello_world::devices::motor::kStateIdDismatch, hello_world::devices::motor::kStateOk, hello_world::devices::motor::kVelBits, hello_world::devices::motor::Motor::last_raw_angle_, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::Motor::normAngle, PI, raw2curr, raw2torq, hello_world::devices::motor::MotorBaseInfo::redu_rat, hello_world::devices::motor::Motor::round_, hello_world::devices::motor::MotorInfo::rx_id, temp_, hello_world::devices::motor::Motor::torq_, hello_world::devices::motor::Motor::vel_.
float hello_world::devices::motor::DM_J4310::raw2torq(float raw) const override
将原始报文内容转换为输出端力矩
raw 原始报文数值 原始报文对应的输出端力矩值，单位：N·m 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::_Uint2Float, hello_world::devices::motor::kMaxTorq, hello_world::devices::motor::kTorqBits, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::MotorBaseInfo::redu_rat.
Referenced by decode, setInput.
float hello_world::devices::motor::DM_J4310::torq2raw(float torq) const override
将输出端力矩转换为原始报文内容
torq 输出端力矩值，单位：N·m 输出端力矩值对应的原始报文 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::_Float2Uint, hello_world::devices::motor::kMaxTorq, hello_world::devices::motor::kTorqBits, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::MotorBaseInfo::redu_rat, hello_world::devices::motor::Motor::torq.
Referenced by setInput.
float hello_world::devices::motor::DM_J4310::raw2curr(float raw) const override
将原始报文内容转换为转子电流
raw 原始报文数值 原始报文对应的转子电流值，单位：A 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::_Uint2Float, hello_world::devices::motor::kMaxTorq, hello_world::devices::motor::kTorqBits, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::MotorBaseInfo::torq_const.
Referenced by decode.
float hello_world::devices::motor::DM_J4310::curr2raw(float curr) const override
将转子电流转换为原始报文内容
curr 转子电流值，单位：A 转子电流值对应的原始报文 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::_Float2Uint, hello_world::devices::motor::Motor::curr, hello_world::devices::motor::kMaxTorq, hello_world::devices::motor::kTorqBits, hello_world::devices::motor::Motor::motor_info_, hello_world::devices::motor::MotorBaseInfo::torq_const.
Referenced by setInput.
uint8_t hello_world::devices::motor::DM_J4310::temp(void) const
References temp_.