hello_world::devices::buzzer::Buzzer
TIM_HandleTypeDef* const hello_world::devices::buzzer::Buzzer::kHtim_
Referenced by Buzzer, mute, play, setNewTune.
const uint32_t hello_world::devices::buzzer::Buzzer::kChannel_
Referenced by Buzzer, mute, play, setNewTune.
const TuneListInfo* hello_world::devices::buzzer::Buzzer::kTuneListInfoPtr_
Referenced by play, setNewTune.
size_t hello_world::devices::buzzer::Buzzer::tune_idx_
Referenced by play, setNewTune.
uint32_t hello_world::devices::buzzer::Buzzer::tune_start_tick_
Referenced by play, setNewTune.
PlayConfig hello_world::devices::buzzer::Buzzer::play_config_
Referenced by get_play_config, play, set_play_config.
bool hello_world::devices::buzzer::Buzzer::tune_switch_
Referenced by play, setNewTune.
bool hello_world::devices::buzzer::Buzzer::is_playing_
Referenced by is_playing, play, setNewTune.
bool hello_world::devices::buzzer::Buzzer::last_is_playing_
Referenced by play, setNewTune.
hello_world::devices::buzzer::Buzzer::Buzzer(TIM_HandleTypeDef *htim, uint32_t channel, PlayConfig play_config, const TuneListInfo *kTuneListInfoPtr)
蜂鸣器初始化
PWM 最大占空比 htim 定时器句柄指针 channel 定时器PWM对应输出通道 kTuneListInfoPtr 乐曲信息指针， 请确保播放期间指针所指内容没有被释放 None 使用前请先确保定时器的频率为 1MHz， 声音强度与播放的音符会被自行限定到合理取值范围中，蜂鸣器默认开启
References HW_ASSERT, kChannel_, kHtim_, hello_world::devices::buzzer::kPlayConfigLoopPlayback, hello_world::devices::buzzer::kPlayConfigSinglePlayback, setNewTune.
virtual hello_world::devices::buzzer::Buzzer::~Buzzer()
bool hello_world::devices::buzzer::Buzzer::is_playing(void) const
References is_playing_.
PlayConfig hello_world::devices::buzzer::Buzzer::get_play_config(void) const
References play_config_.
void hello_world::devices::buzzer::Buzzer::set_play_config(PlayConfig play_config)
References HW_ASSERT, hello_world::devices::buzzer::kPlayConfigLoopPlayback, hello_world::devices::buzzer::kPlayConfigSinglePlayback, play_config_.
void hello_world::devices::buzzer::Buzzer::mute(void) const
关闭蜂鸣器
None None
References kChannel_, kHtim_.
Referenced by play.
void hello_world::devices::buzzer::Buzzer::play(void)
播放乐曲
None 请确保该方法以至少 1kHz 的频率被调用
References hello_world::Bound, hello_world::dsp::tick::GetTickMs, hello_world::devices::buzzer::TuneListInfo::intensity_scale, is_playing_, kChannel_, kHtim_, hello_world::devices::buzzer::kMaxDuty, hello_world::devices::buzzer::kPlayConfigLoopPlayback, hello_world::devices::buzzer::kTuneEnd, kTuneListInfoPtr_, hello_world::devices::buzzer::kTuneListMaxLen, last_is_playing_, hello_world::devices::buzzer::TuneListInfo::list, mute, play_config_, tune2AutoReload, hello_world::devices::buzzer::TuneListInfo::tune_duration, tune_idx_, tune_start_tick_, tune_switch_.
void hello_world::devices::buzzer::Buzzer::setNewTune(const TuneListInfo *kTuneListInfoPtr)
设置新的乐曲信息
kTuneListInfoPtr 乐曲信息指针， 请确保播放期间指针所指内容没有被释放 None 使用前请先确保定时器的频率为 1MHz， 声音强度与播放的音符会被自行限定到合理取值范围中，调用后蜂鸣器会自动开启
References is_playing_, kChannel_, kHtim_, kTuneListInfoPtr_, last_is_playing_, tune_idx_, tune_start_tick_, tune_switch_.
Referenced by Buzzer.
uint32_t hello_world::devices::buzzer::Buzzer::tune2AutoReload(Tune tune) const
将音符转化为对应的定时器重载值
tune 音符 对应的定时器重载值 音符会被自行限定到合理取值范围中
References hello_world::devices::buzzer::kTimerFreq, hello_world::devices::buzzer::kTuneRst.
Referenced by play.