hello_world::algorithms::controller::pid::BasicPid
typedef BasicPidParams hello_world::algorithms::controller::pid::BasicPid::Params
typedef BasicPidDatas hello_world::algorithms::controller::pid::BasicPid::Datas
Params hello_world::algorithms::controller::pid::BasicPid::params_
参数
Referenced by BasicPid, calc, params, params.
Datas hello_world::algorithms::controller::pid::BasicPid::datas_
数据
Referenced by calc, datas, out, reset.
hello_world::algorithms::controller::pid::BasicPid::BasicPid()
默认构造函数，初始化 Controller 基类
参考值维数、反馈值维数、前馈值维数和输出值维数均为 1。
hello_world::algorithms::controller::pid::BasicPid::BasicPid(const Params &params)
构造函数，初始化 Controller 基类并设置 PID 参数
params PID 参数
hello_world::algorithms::controller::pid::BasicPid::BasicPid(float kp, float ki, float kd)
构造函数，初始化 Controller 基类并设置 PID 参数
kp 比例系数 ki 积分系数 kd 微分系数
References hello_world::algorithms::controller::pid::BasicPidParams::kd, hello_world::algorithms::controller::pid::BasicPidParams::ki, hello_world::algorithms::controller::pid::BasicPidParams::kp, params_.
float hello_world::algorithms::controller::pid::BasicPid::out() const
获取 PID 控制器的输出
PID 控制器的输出
References datas_, hello_world::algorithms::controller::pid::BasicPidDatas::out.
Referenced by calc.
State hello_world::algorithms::controller::pid::BasicPid::reset() override
重置PID数据
始终返回 kStateOk
References datas_, hello_world::algorithms::controller::kStateOk.
Referenced by calc, hello_world::algorithms::controller::pid::MultiNodesPid::reset.
State hello_world::algorithms::controller::pid::BasicPid::calc(const float *ref_ls, const float *fdb_ls, const float *ffd_ls, float *out_ls) override
PID 控制器的计算函数
ref_ls 参考值列表，只使用第一个值，如果为nullptr则使用 0 fdb_ls 反馈值列表，只使用第一个值，如果为nullptr则使用 0 ffd_ls 前馈值列表，只使用第一个值，如果为nullptr则使用 0 out_ls 输出值列表，只使用第一个值，为 nullptr 时，输出传递失败 表示计算过程是否正常的状态值 kStateOk 计算成功且所有参数均不为nullptr kStateError 有参数为 nullptr，为了计算成功会使用默认值 - 当 ref_ls 为 nullptr 时，使用 0 作为参考值 - 当 fdb_ls 为 nullptr 时，使用 0 作为反馈值 - 当 ffd_ls 为 nullptr 时，使用 0 作为前馈值 - 当 out_ls 为 nullptr 时，输出传递失败
References hello_world::algorithms::controller::pid::BasicPidParams::across0, hello_world::algorithms::controller::pid::BasicPidParams::auto_reset, hello_world::algorithms::controller::pid::DiffFilter::calc, hello_world::algorithms::controller::pid::InteSeparation::calc, hello_world::algorithms::controller::pid::InteChangingRate::calc, hello_world::algorithms::controller::pid::DeadBand::calc, hello_world::algorithms::controller::pid::InteTrapezoidal::calc, hello_world::algorithms::controller::pid::InteAntiWindup::calc, hello_world::algorithms::controller::pid::DiffPrevious::calc, hello_world::algorithms::controller::pid::OutLimit::calc, hello_world::algorithms::controller::pid::SetpointRamping::calc, datas_, hello_world::algorithms::controller::pid::BasicPidParams::dead_band, hello_world::algorithms::controller::pid::BasicPidDatas::diff, hello_world::algorithms::controller::pid::BasicPidParams::diff_filter, hello_world::algorithms::controller::pid::BasicPidParams::diff_previous, hello_world::algorithms::controller::pid::BasicPidDatas::err, hello_world::algorithms::controller::pid::BasicPidDatas::fdb, hello_world::algorithms::controller::pid::BasicPidDatas::ff, hello_world::dsp::tick::GetTickMs, hello_world::algorithms::controller::pid::HandleAcross0, hello_world::algorithms::controller::pid::BasicPidDatas::inte, hello_world::algorithms::controller::pid::BasicPidParams::inte_anti_windup, hello_world::algorithms::controller::pid::BasicPidParams::inte_changing_rate, hello_world::algorithms::controller::pid::BasicPidParams::inte_separation, hello_world::algorithms::controller::pid::BasicPidParams::inte_trapezoidal, hello_world::algorithms::controller::pid::BasicPidDatas::interval_s, hello_world::algorithms::controller::pid::BasicPidParams::kd, hello_world::algorithms::controller::pid::BasicPidParams::ki, hello_world::algorithms::controller::pid::BasicPidParams::kp, hello_world::algorithms::controller::kStateError, hello_world::algorithms::controller::kStateOk, hello_world::algorithms::controller::pid::BasicPidDatas::last_err, hello_world::algorithms::controller::pid::BasicPidDatas::last_fdb, hello_world::algorithms::controller::pid::BasicPidDatas::last_out, hello_world::algorithms::controller::pid::BasicPidDatas::last_ref, hello_world::algorithms::controller::pid::BasicPidDatas::last_tick, hello_world::algorithms::controller::pid::BasicPidParams::max_interval_ms, hello_world::algorithms::controller::pid::BasicPidDatas::out, out, hello_world::algorithms::controller::pid::BasicPidParams::out_limit, params_, hello_world::algorithms::controller::pid::BasicPidDatas::prop, hello_world::algorithms::controller::pid::BasicPidDatas::ref, reset, hello_world::algorithms::controller::pid::BasicPidParams::setpointe_ramping.
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::cascade_calc, hello_world::algorithms::controller::pid::MultiNodesPid::parallel_calc.
const Params & hello_world::algorithms::controller::pid::BasicPid::params() const
获取 PID 参数的常量引用
PID 参数的常量引用
References params_.
Referenced by hello_world::algorithms::controller::pid::MultiNodesPid::paramsAt, hello_world::algorithms::controller::pid::PidList::push.
Params & hello_world::algorithms::controller::pid::BasicPid::params()
获取 PID 参数的引用，用于修改参数，修改方法参见 BasicPidParams
PID 参数的引用
References params_.
const Datas & hello_world::algorithms::controller::pid::BasicPid::datas() const
获取 PID 数据的常量引用
PID 数据的常量引用
References datas_.