hello_world::devices::motor::Motor
float hello_world::devices::motor::Motor::angle_
电机状态
Referenced by angle, hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.
float hello_world::devices::motor::Motor::vel_
电机输出端角度，单位：rad
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, vel.
float hello_world::devices::motor::Motor::torq_
电机输出单角速度，单位：rad/s
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, torq.
float hello_world::devices::motor::Motor::curr_
电机输出端实际力矩，单位：N·m
Referenced by curr, hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.
float hello_world::devices::motor::Motor::round_
电机转子实际电流，单位：A
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.
float hello_world::devices::motor::Motor::last_raw_angle_
电机转子端累计圈数
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.
float hello_world::devices::motor::Motor::actual_angle_
电机输出端实际输出角度（未扣除角度偏差），单位：rad
电机上次角度原始值
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, setAngleValue.
float hello_world::devices::motor::Motor::raw_input_
电机输入
Referenced by hello_world::devices::motor::A1::encode, hello_world::devices::motor::DM_J4310::encode, hello_world::devices::motor::GM6020::encode, hello_world::devices::motor::M2006::encode, hello_world::devices::motor::M3508::encode, hello_world::devices::motor::M8910::encode, hello_world::devices::motor::MF9025v2::encode, getInput, setInput, hello_world::devices::motor::DM_J4310::setInput, hello_world::devices::motor::GM6020::setInput.
float hello_world::devices::motor::Motor::torq_input_
报文原始输入
Referenced by getInput, setInput, hello_world::devices::motor::DM_J4310::setInput.
float hello_world::devices::motor::Motor::curr_input_
电机输出端期望力矩
Referenced by getInput, setInput, hello_world::devices::motor::DM_J4310::setInput.
MotorInfo hello_world::devices::motor::Motor::motor_info_
电机转子期望电流
Referenced by hello_world::devices::motor::A1::A1, angle_range, curr2raw, hello_world::devices::motor::DM_J4310::curr2raw, curr2torq, hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, dir, hello_world::devices::motor::DM_J4310::DM_J4310, hello_world::devices::motor::A1::encode, hello_world::devices::motor::DM_J4310::encode, hello_world::devices::motor::GM6020::encode, hello_world::devices::motor::M2006::encode, hello_world::devices::motor::M3508::encode, hello_world::devices::motor::M8910::encode, hello_world::devices::motor::MF9025v2::encode, get_input_type, getInput, hello_world::devices::motor::GM6020::GM6020, id, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2, motor_info, normAngle, raw2curr, hello_world::devices::motor::DM_J4310::raw2curr, raw2torq, hello_world::devices::motor::DM_J4310::raw2torq, rx_id, set_input_type, hello_world::devices::motor::GM6020::set_input_type, setAngleValue, setInput, hello_world::devices::motor::DM_J4310::setInput, hello_world::devices::motor::GM6020::setInput, torq2curr, torq2raw, hello_world::devices::motor::DM_J4310::torq2raw, tx_id.
constexpr float hello_world::devices::motor::Motor::kCross0ValueThres
电机状态
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.
hello_world::devices::motor::Motor::Motor()
virtual hello_world::devices::motor::Motor::~Motor()
State hello_world::devices::motor::Motor::setInput(float input)
设定发给电调的期望值
input 发给电调的期望值 运行状态 1. 期望值的物理意义与电机当前的输入类型有关，可使用 get_input_type 方法查看 设定的期望值会自动被限制到允许的范围内，当前实际的设定值可以通 过 getInput 方法查看
References hello_world::Bound, curr2raw, curr2torq, curr_input_, hello_world::devices::motor::MotorBaseInfo::curr_input_lim, hello_world::devices::motor::MotorInfo::input_type, hello_world::devices::motor::kInputTypeCurr, hello_world::devices::motor::kInputTypeRaw, hello_world::devices::motor::kInputTypeTorq, hello_world::devices::motor::kStateInputTypeError, hello_world::devices::motor::kStateInputValueOverflow, hello_world::devices::motor::kStateOk, motor_info_, raw2curr, raw2torq, raw_input_, hello_world::devices::motor::MotorBaseInfo::raw_input_lim, torq2curr, torq2raw, torq_input_, hello_world::devices::motor::MotorBaseInfo::torq_input_lim.
float hello_world::devices::motor::Motor::getInput(void) const
获取发给电调的期望值
发给电调的期望值 期望值的物理意义与电机当前的输入类型有关，可使用 get_input_type 方法查看
References curr_input_, hello_world::devices::motor::MotorInfo::input_type, hello_world::devices::motor::kInputTypeCurr, hello_world::devices::motor::kInputTypeRaw, hello_world::devices::motor::kInputTypeTorq, motor_info_, raw_input_, torq_input_.
void hello_world::devices::motor::Motor::setAngleValue(float angle)
将当前电机输出端所处位置设置为指定的角度
angle 指定角度，单位：rad None None
References actual_angle_, angle, hello_world::devices::motor::MotorInfo::angle_offset, motor_info_.
virtual State hello_world::devices::motor::Motor::encode(uint8_t tx_data[8], uint32_t tx_msg_std_id) const =0
将要发给电调的期望输值编码为对应的 CAN 报文
tx_data 将要发出的 CAN 报文 tx_msg_std_id 发给电调的报文的ID 当 ID 匹配时返回 kStateOk，否则返回 kStateIdDismatch 1. 只有当 tx_msg_std_id 与实际的发给电机报文的 ID 对应时才会生成 报文，该 ID 可以通过 tx_id 方法获取 只会在报文需要的位置上进行修改，区域位置的内容会保持不变
virtual State hello_world::devices::motor::Motor::decode(const uint8_t rx_data[8], uint32_t rx_msg_std_id)=0
将电调发回的 CAN 报文进行解包
rx_data 电调发回的 CAN 报文 rx_msg_std_id 电调发回的报文的ID 当 ID 匹配时返回 kStateOk，否则返回 kStateIdDismatch 只有当 rx_msg_std_id 与实际的电机会发回报文的 ID 对应时才会对报文 进行解包，该 ID 可以通过 rx_id 方法获取
float hello_world::devices::motor::Motor::raw2torq(float raw) const
将原始报文内容转换为输出端力矩
raw 原始报文数值 原始报文对应的输出端力矩值，单位：N·m 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::MotorBaseInfo::curr_rat, hello_world::devices::motor::kRawMappingTypeCurr, hello_world::devices::motor::kRawMappingTypeTorq, motor_info_, hello_world::devices::motor::MotorBaseInfo::raw_mapping_type, hello_world::devices::motor::MotorBaseInfo::redu_rat, hello_world::devices::motor::MotorBaseInfo::torq_const, hello_world::devices::motor::MotorBaseInfo::torq_rat.
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::A1::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2, setInput.
float hello_world::devices::motor::Motor::torq2raw(float torq) const
将输出端力矩转换为原始报文内容
torq 输出端力矩值，单位：N·m 输出端力矩值对应的原始报文 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::MotorBaseInfo::curr_rat, hello_world::devices::motor::kRawMappingTypeCurr, hello_world::devices::motor::kRawMappingTypeTorq, motor_info_, hello_world::devices::motor::MotorBaseInfo::raw_mapping_type, hello_world::devices::motor::MotorBaseInfo::redu_rat, torq, hello_world::devices::motor::MotorBaseInfo::torq_const, hello_world::devices::motor::MotorBaseInfo::torq_rat.
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2, setInput.
float hello_world::devices::motor::Motor::raw2curr(float raw) const
将原始报文内容转换为转子电流
raw 原始报文数值 原始报文对应的转子电流值，单位：A 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References hello_world::devices::motor::MotorBaseInfo::curr_rat, hello_world::devices::motor::kRawMappingTypeCurr, hello_world::devices::motor::kRawMappingTypeTorq, motor_info_, hello_world::devices::motor::MotorBaseInfo::raw_mapping_type, hello_world::devices::motor::MotorBaseInfo::torq_const, hello_world::devices::motor::MotorBaseInfo::torq_rat.
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::A1::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2, setInput.
float hello_world::devices::motor::Motor::curr2raw(float curr) const
将转子电流转换为原始报文内容
curr 转子电流值，单位：A 转子电流值对应的原始报文 报文的对应的物理意义需要与设定的相符，设定对应情可以通过 motor_info 方法获取电机信息结构体，查看其中的 raw_mapping_type 变量
References curr, hello_world::devices::motor::MotorBaseInfo::curr_rat, hello_world::devices::motor::kRawMappingTypeCurr, hello_world::devices::motor::kRawMappingTypeTorq, motor_info_, hello_world::devices::motor::MotorBaseInfo::raw_mapping_type, hello_world::devices::motor::MotorBaseInfo::torq_const, hello_world::devices::motor::MotorBaseInfo::torq_rat.
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2, setInput.
float hello_world::devices::motor::Motor::torq2curr(float torq) const
将输出端力矩转换为转子电流
torq 输出端力矩值，单位：N·m 输出端力矩值对应的转子电流，单位：A None
References motor_info_, hello_world::devices::motor::MotorBaseInfo::redu_rat, torq, hello_world::devices::motor::MotorBaseInfo::torq_const.
Referenced by hello_world::devices::motor::DM_J4310::DM_J4310, setInput, hello_world::devices::motor::DM_J4310::setInput.
float hello_world::devices::motor::Motor::curr2torq(float curr) const
将转子电流转换为输出端力矩
curr 转子电流值，单位：A 转子电流值对应的输出端力矩，单位：N·m None
References curr, motor_info_, hello_world::devices::motor::MotorBaseInfo::redu_rat, hello_world::devices::motor::MotorBaseInfo::torq_const.
Referenced by hello_world::devices::motor::DM_J4310::DM_J4310, setInput, hello_world::devices::motor::DM_J4310::setInput.
const MotorInfo & hello_world::devices::motor::Motor::motor_info(void) const
References motor_info_.
Dir hello_world::devices::motor::Motor::dir(void) const
References hello_world::devices::motor::MotorInfo::dir, motor_info_.
uint8_t hello_world::devices::motor::Motor::id(void) const
References hello_world::devices::motor::MotorInfo::id, motor_info_.
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::DM_J4310::DM_J4310, hello_world::devices::motor::GM6020::GM6020, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2.
uint32_t hello_world::devices::motor::Motor::rx_id(void) const
References motor_info_, hello_world::devices::motor::MotorInfo::rx_id.
uint32_t hello_world::devices::motor::Motor::tx_id(void) const
References motor_info_, hello_world::devices::motor::MotorInfo::tx_id.
AngleRange hello_world::devices::motor::Motor::angle_range(void) const
References hello_world::devices::motor::MotorInfo::angle_range, motor_info_.
State hello_world::devices::motor::Motor::set_input_type(InputType input_type)
设置点击的输入类型
input_type 期望输入类型 kInputTypeRaw: 原始报文输入 kInputTypeTorq: 输出端力矩输入 kInputTypeCurr: 转子端电流输入 None None
References hello_world::devices::motor::MotorInfo::input_type, hello_world::devices::motor::kInputTypeCurr, hello_world::devices::motor::kInputTypeRaw, hello_world::devices::motor::kInputTypeTorq, hello_world::devices::motor::kStateInputTypeError, hello_world::devices::motor::kStateOk, motor_info_.
InputType hello_world::devices::motor::Motor::get_input_type(void) const
References hello_world::devices::motor::MotorInfo::input_type, motor_info_.
float hello_world::devices::motor::Motor::angle(void) const
References angle_.
Referenced by hello_world::devices::motor::DM_J4310::decode, normAngle, setAngleValue.
float hello_world::devices::motor::Motor::vel(void) const
References vel_.
float hello_world::devices::motor::Motor::torq(void) const
References torq_.
Referenced by torq2curr, torq2raw, hello_world::devices::motor::DM_J4310::torq2raw.
float hello_world::devices::motor::Motor::curr(void) const
References curr_.
Referenced by curr2raw, hello_world::devices::motor::DM_J4310::curr2raw, curr2torq.
float hello_world::devices::motor::Motor::normAngle(float angle)
将角度转换到指定范围
过零阈值 angle 待转换的角度，单位：rad 归一化后的角度，单位：rad None
References angle, hello_world::devices::motor::MotorInfo::angle_range, hello_world::devices::motor::kAngleRange0To2Pi, hello_world::devices::motor::kAngleRangeNegInfToPosInf, hello_world::devices::motor::kAngleRangeNegPiToPosPi, motor_info_, hello_world::NormPeriodData, PI.
Referenced by hello_world::devices::motor::A1::decode, hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::GM6020::decode, hello_world::devices::motor::M2006::decode, hello_world::devices::motor::M3508::decode, hello_world::devices::motor::M8910::decode, hello_world::devices::motor::MF9025v2::decode.