hello_world::dsp::tick
uint32_t hello_world::dsp::tick::start_tick_us
Referenced by GetTickUs.
uint32_t hello_world::dsp::tick::GetTickUs()
References start_tick_us.
Referenced by GetTickMs.
uint32_t hello_world::dsp::tick::GetTickMs()
References GetTickUs.
Referenced by hello_world::algorithms::controller::pid::BasicPid::calc, hello_world::devices::referee::RxPackage< T >::decode, GetTickS, hello_world::devices::referee::RxPackageInfo::isUpdated, hello_world::devices::buzzer::Buzzer::play.
uint32_t hello_world::dsp::tick::GetTickS()
References GetTickMs.