hello_world::devices::referee
FramePartLength
FramePartIndex
InterAmongRobotsId
InterAmongRobotsDataLength
FrameCmdId
FrameDataLength
FrameFrequence
CompetitionType
CompetitionStage
CompetitionResults
SupplierId
Official Projectile Supplier Outlet to the left of own side (facing the Official Projectile Supplier)
SupplingRobotIds
No robot is reloading projectiles
SupplierStep
Status of the projectile outlet is closed.
SuppliedNumber
Number of supplied projectiles is 50
PenaltyLevel
AirforceStatus
Aerial robot status is cooling
HpDeductionReason
HP deduction due to Armor being hit by projectiles
DartStationStatus
The Dart Station is closed.
DartTarget
Dart target is outpost (Outpost as default).
RobotId
ClientId
UiSubCmdId
DeleteLayerOperation
LayerNumber
GraphicOperation
GraphicType
GraphicColor
UiRefeshPriority
typedef uint8_t hello_world::devices::referee::Crc8_t
typedef uint16_t hello_world::devices::referee::Crc16_t
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterRadarWarning
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::FrameHeader
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::CompetitionStatus
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::CompetitionResult
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::CompetitionRobotsHp
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::TeamEvent
typedef enum hello_world::devices::referee::SupplingRobotIds hello_world::devices::referee::SupplingRobotId
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::TeamSupplierAction
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::TeamRefereeWarning
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotDartStatus
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotPerformance
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotPowerHeat
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotPosition
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotBuff
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotAerialStatus
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotDamage
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotShootData
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotProjectileAllowance
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotRfid
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotDartClientCommand
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotsGroundPosition
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::RobotRadarMarkProgress
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterFrameHeader
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterDeleteLayer
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphic
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphicPack1
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphicPack2
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphicPack5
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphicPack7
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterGraphicPackCharacter
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterCustomCtrllerToRobot
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterClientMapToRobots
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::MainCtrllerKeyboardData
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterCtrllerToRobot
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterRadarMapToClient
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterCustomCtrllerToClient
typedef struct hello_world::devices::referee::__REFEREE_PACKED hello_world::devices::referee::InterSentryTrajectoryToClient
const size_t hello_world::devices::referee::kRefereeMaxBuffer
Referenced by hello_world::devices::referee::Referee::encodeFrame, hello_world::devices::referee::Referee::processByte.
const uint8_t hello_world::devices::referee::kRefereeFrameHeaderSof
Referenced by hello_world::devices::referee::Referee::encodeFrame, hello_world::devices::referee::Referee::processByte.
const uint32_t hello_world::devices::referee::kMaxPositionX
const uint32_t hello_world::devices::referee::kMaxPositionY
const int16_t hello_world::devices::referee::kIllegalUiElementProperty
const uint8_t hello_world::devices::referee::kCrc8Init
Referenced by SetEndCrc8CheckSum, VerifyCrc8CheckSum.
const uint8_t hello_world::devices::referee::kCrc8Table[256][256]
Referenced by GetCrc8CheckSum.
const uint16_t hello_world::devices::referee::kCrc16Init
Referenced by SetEndCrc16CheckSum, VerifyCrc16CheckSum.
const uint16_t hello_world::devices::referee::kCrc16Table[256][256]
Referenced by GetCrc16CheckSum.
bool hello_world::devices::referee::VerifyCrc8CheckSum(uint8_t *p_message, uint32_t length)
Verifies the CRC8 checksum of a message.
This function calculates the expected CRC8 checksum of the input message and compares it to the last byte of the message to verify its integrity. p_message[uint8_t *] Pointer to the message data. length[uint32_t] Length of the message in bytes. true if the CRC8 checksum matches the last byte of the message, false otherwise.
References GetCrc8CheckSum, kCrc8Init.
Referenced by hello_world::devices::referee::Referee::processByte.
bool hello_world::devices::referee::SetEndCrc8CheckSum(uint8_t *p_message, uint32_t length)
Set the last byte of a message to a CRC8 checksum.
This function calculates the CRC8 checksum of the input message and sets it as the last byte of the message. p_message Pointer to the message data. length Length of the message in bytes. true if the CRC8 checksum is successfully set as the last byte, false otherwise.
References GetCrc8CheckSum, kCrc8Init.
Referenced by hello_world::devices::referee::Referee::encodeSetCrc.
bool hello_world::devices::referee::VerifyCrc16CheckSum(uint8_t *p_message, uint32_t length)
Verifies the CRC16 checksum of a message.
This function calculates the expected CRC16 checksum of the input message and compares it to the last two bytes of the message to verify its integrity. p_message Pointer to the message data. length Length of the message in bytes. true if the CRC16 checksum matches the last two bytes of the message, false otherwise.
References GetCrc16CheckSum, kCrc16Init.
Referenced by hello_world::devices::referee::Referee::processByte.
bool hello_world::devices::referee::SetEndCrc16CheckSum(uint8_t *p_message, uint32_t length)
Set the last two bytes of a message to a CRC16 checksum.
This function calculates the CRC16 checksum of the input message and sets it as the last two bytes of the message. p_message Pointer to the message data. length Length of the message in bytes. true if the CRC16 checksum is successfully set as the last two bytes, false otherwise.
References GetCrc16CheckSum, kCrc16Init.
Referenced by hello_world::devices::referee::Referee::encodeSetCrc.
uint8_t hello_world::devices::referee::GetCrc8CheckSum(uint8_t *p_message, uint32_t length, uint8_t crc8_init)
Calculate and return the CRC8 checksum of a message.
This function iterates through the input message and computes the CRC8 checksum using the provided CRC8 initialization value. p_message Pointer to the message data. length Length of the message in bytes. crc8_init Initial CRC8 value to start the checksum calculation. uint8_t Calculated CRC8 checksum for the message.
References kCrc8Table.
Referenced by SetEndCrc8CheckSum, VerifyCrc8CheckSum.
uint16_t hello_world::devices::referee::GetCrc16CheckSum(uint8_t *p_message, uint32_t length, uint16_t crc16_init)
Calculate and return the CRC16 checksum of a message.
This function iterates through the input message and computes the CRC16 checksum using the provided CRC16 initialization value. p_message Pointer to the message data. length Length of the message in bytes. crc8_init Initial CRC16 value to start the checksum calculation. Calculated CRC16 checksum for the message.
References kCrc16Table.
Referenced by SetEndCrc16CheckSum, VerifyCrc16CheckSum.