hello_world
WheelType
const float hello_world::kGravAcc
Referenced by hello_world::devices::imu::BMI088::accSelfTest.
const float hello_world::kRad2DegCoff
重力加速度（杭州）
Referenced by Rad2Deg.
const float hello_world::kDeg2RadCoff
Referenced by Deg2Rad.
uint8_t hello_world::GetSign(T x)
获取变量的符号
x 输入变量 输入变量的符号 只有支持大小比较的变量才可使用该函数
T hello_world::Max(T x1, T x2)
获取两个变量间的最大值
x1 比较变量1 x2 比较变量1 二者间的最大值 只有支持大小比较的变量才可使用该函数
T hello_world::Min(T x1, T x2)
获取两个变量间的最小值
x1 比较变量1 x2 比较变量1 二者间的最小值 只有支持大小比较的变量才可使用该函数
Referenced by hello_world::devices::motor::A1::A1, hello_world::devices::motor::DM_J4310::DM_J4310, hello_world::devices::motor::GM6020::GM6020, hello_world::devices::motor::M2006::M2006, hello_world::devices::motor::M3508::M3508, hello_world::devices::motor::M8910::M8910, hello_world::devices::motor::MF9025v2::MF9025v2.
T1 hello_world::Bound(T1 x, T2 lim1, T3 lim2)
将输入值限制在一个范围内
x 待范围限制变量 lim1 范围边界1 lim2 范围边界2 范围限制后的值 无需考虑两个范围边界的相对大小关系，变量需要支持大小比较
Referenced by hello_world::devices::servo::Servo::angle2Cmp, hello_world::devices::motor::A1::encode, hello_world::devices::motor::DM_J4310::encode, hello_world::devices::motor::GM6020::encode, hello_world::devices::motor::M2006::encode, hello_world::devices::motor::M3508::encode, hello_world::devices::motor::M8910::encode, hello_world::devices::motor::MF9025v2::encode, hello_world::devices::laser::Laser::luminPct2Cmp, hello_world::devices::buzzer::Buzzer::play, hello_world::devices::motor::Motor::setInput, hello_world::devices::motor::DM_J4310::setInput, hello_world::devices::motor::GM6020::setInput.
bool hello_world::IsInRange(T x, T bound1, T bound2)
判断变量是否位于给定的范围内
bound1 范围边界1（含） bound2 范围边界2（含） 变量是否位于给定的范围内 无需考虑两个范围边界的相对大小关系，变量需要支持大小比较
float hello_world::NormPeriodData(float period_lb, float period_ub, float data)
将周期性数据归一化到指定周期区间
period_lb 周期区间下界（含） period_ub 周期区间上界 data 待归一化数据 归一化后的数据 period_lb 必须小于 period_ub
References HW_ASSERT.
Referenced by AngleNormDeg, AngleNormRad, hello_world::devices::motor::Motor::normAngle.
float hello_world::PeriodData2SameRegion(float period_lb, float period_ub, float ref_data, float data)
将待处理数据平移到参考数据的所在周期中
period_lb 周期区间下界（含） period_ub 周期区间上界 ref_data 参考数据（无需再周期区间之内） data 待处理数据 平移后的数据 period_lb 必须小于 period_ub
References HW_ASSERT.
float hello_world::PeriodData2NearestDist(float period, float ref_data, float data)
将待处理数据平移到距离参考数据最近的值
period 周期 ref_data 参考数据 data 待处理数据 平移后的数据 None
References HW_ASSERT.
float hello_world::AngleNormRad(float angle)
将角度归一化到[-π, π)
angle 待归一化角度，单位：rad 归一化后的角度，单位：rad None
References NormPeriodData, PI.
float hello_world::AngleNormDeg(float angle)
将角度归一化到[-180°, 180°)
angle 待归一化角度，单位：deg 归一化后的角度，单位：deg None
References NormPeriodData.
float hello_world::PeriodDataSub(float minuend, float subtrahend, float period)
处理角度越过0值的情况，以半周期为基准
ref 指向目标角度的指针 fdb 实际反馈的角度值 period 角度值的周期，通常是180度 处理角度越过0值的情况，确保目标角度和实际反馈的角度值在同一半周期内。 如果目标角度 - 实际反馈的角度 >= half_period，则减去2 * half_period，确保在同一半周期内。 如果目标角度 - 实际反馈的角度 < -half_period，则加上2 * half_period，确保在同一半周期内。
References HW_ASSERT.
Referenced by HandleAngleCross0Deg, HandleAngleCross0Rad.
float hello_world::HandleAngleCross0Rad(float ref, float fdb)
References PeriodDataSub, PI.
Referenced by hello_world::algorithms::controller::pid::HandleAcross0.
float hello_world::HandleAngleCross0Deg(float ref, float fdb)
References PeriodDataSub.
Referenced by hello_world::algorithms::controller::pid::HandleAcross0.
float hello_world::Rad2Deg(float angle)
将弧度制角度转换为角度制
angle 待转换角度，单位：rad 输入角度的角度制表示 None
References kRad2DegCoff.
float hello_world::Deg2Rad(float angle)
将角度制角度转换为弧度制
angle 待转换角度，单位：deg 输入角度的弧度制表示 None
References kDeg2RadCoff.