hello_world::devices::motor
MotorType
State
InputType
RawMappingType
Dir
电机转动正方向与规定正方向的关系
AngleRange
const float hello_world::devices::motor::kInvalidValue
Referenced by hello_world::devices::motor::DM_J4310::DM_J4310, hello_world::devices::motor::GM6020::GM6020.
const MotorBaseInfo hello_world::devices::motor::kA1MotorBaseInfo
Referenced by hello_world::devices::motor::A1::A1.
const MotorBaseInfo hello_world::devices::motor::kDM_J4310MotorBaseInfo
Referenced by hello_world::devices::motor::DM_J4310::DM_J4310.
const float hello_world::devices::motor::kMaxAngle
Referenced by hello_world::devices::motor::DM_J4310::decode.
const uint8_t hello_world::devices::motor::kAngleBits
Referenced by hello_world::devices::motor::DM_J4310::decode.
const float hello_world::devices::motor::kMaxVel
Referenced by hello_world::devices::motor::DM_J4310::decode.
const uint8_t hello_world::devices::motor::kVelBits
Referenced by hello_world::devices::motor::DM_J4310::decode.
const float hello_world::devices::motor::kMaxTorq
Referenced by hello_world::devices::motor::DM_J4310::curr2raw, hello_world::devices::motor::DM_J4310::DM_J4310, hello_world::devices::motor::DM_J4310::raw2curr, hello_world::devices::motor::DM_J4310::raw2torq, hello_world::devices::motor::DM_J4310::torq2raw.
const uint8_t hello_world::devices::motor::kTorqBits
Referenced by hello_world::devices::motor::DM_J4310::curr2raw, hello_world::devices::motor::DM_J4310::encode, hello_world::devices::motor::DM_J4310::raw2curr, hello_world::devices::motor::DM_J4310::raw2torq, hello_world::devices::motor::DM_J4310::torq2raw.
const MotorBaseInfo hello_world::devices::motor::kGM6020MotorBaseInfo
Referenced by hello_world::devices::motor::GM6020::GM6020.
const MotorBaseInfo hello_world::devices::motor::kM2006MotorBaseInfo
Referenced by hello_world::devices::motor::M2006::M2006.
const MotorBaseInfo hello_world::devices::motor::kM3508MotorBaseInfo
Referenced by hello_world::devices::motor::M3508::M3508.
const MotorBaseInfo hello_world::devices::motor::kM8910MotorBaseInfo
Referenced by hello_world::devices::motor::M8910::M8910.
const MotorBaseInfo hello_world::devices::motor::kMF9025v2MotorBaseInfo
Referenced by hello_world::devices::motor::MF9025v2::MF9025v2.
Motor * hello_world::devices::motor::CreateMotor(MotorType motor_type, uint8_t id, const OptionalParams &optinal_params)
根据所需的电机类型创建电机并初始化
motor_type 电机类型 kMotorTypeGM6020，kMotorTypeM2006，kMotorTypeM3508， kMotorTypeM8910，kMotorTypeA1，kMotorTypeDM_J4310，kMotorTypeMF9025v2, id 电机 ID optinal_params 电机可选配置参数 创建的电机类指针 返回的电机类是经过内存申请得到的，不使用时需要自行释放内存
References HW_ASSERT, kMotorTypeA1, kMotorTypeDM_J4310, kMotorTypeGM6020, kMotorTypeM2006, kMotorTypeM3508, kMotorTypeM8910, kMotorTypeMF9025v2.
static float hello_world::devices::motor::_Uint2Float(uint16_t x_int, float x_max, float x_min, uint8_t bits)
根据给定的范围和位数，将 uint 转换为 float
x_uint 待转换的 uint x_max 给定范围的最大值 x_min 给定范围的最小值 bits 整形的位数 转换后的 float 变量 该函数仅供 DM_J4310 电机数据处理用
Referenced by hello_world::devices::motor::DM_J4310::decode, hello_world::devices::motor::DM_J4310::raw2curr, hello_world::devices::motor::DM_J4310::raw2torq.
static uint16_t hello_world::devices::motor::_Float2Uint(float x_float, float x_max, float x_min, uint8_t bits)
根据给定的范围和位数，将 float 转换为 uint
x_float 待转换的 float x_max 给定范围的最大值 x_min 给定范围的最小值 bits 整形的位数 转换后的 uint 变量 该函数仅供 DM_J4310 电机数据处理用
Referenced by hello_world::devices::motor::DM_J4310::curr2raw, hello_world::devices::motor::DM_J4310::torq2raw.